In [1]:
import pandas as pd
df=pd.read_csv("/content/sample_data/online_retail.csv")
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
211403,555368,20886,BOX OF 9 PEBBLE CANDLES,6,2011-06-02 14:30:00,1.95,13437.0,United Kingdom
211404,555368,22969,HOMEMADE JAM SCENTED CANDLES,12,2011-06-02 14:30:00,1.45,13437.0,United Kingdom
211405,555368,85174,S/4 CACTI CANDLES,4,2011-06-02 14:30:00,4.95,13437.0,United Kingdom
211406,555368,22928,YELLOW GIANT GARDEN THERMOMETER,2,2011-06-02 14:30:00,5.95,13437.0,United Kingdom
211407,555368,22927,GREEN GIANT GARDEN THERMOMETER,2,2011-06-0,NaN,NaN,NaN

In [2]:
df.head(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,2010-12-01 08:26:00,7.65,17850.0,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,2010-12-01 08:26:00,4.25,17850.0,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom
8,536366,22632,HAND WARMER RED POLKA DOT,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,2010-12-01 08:34:00,1.69,13047.0,United Kingdom

In [3]:
df.tail(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
211398,555368,21873,IF YOU CAN'T STAND THE HEAT MUG,12,2011-06-02 14:30:00,1.25,13437.0,United Kingdom
211399,555368,21537,RED RETROSPOT PUDDING BOWL,4,2011-06-02 14:30:00,4.25,13437.0,United Kingdom
211400,555368,82486,WOOD S/3 CABINET ANT WHITE FINISH,2,2011-06-02 14:30:00,8.95,13437.0,United Kingdom
211401,555368,22782,SET 3 WICKER STORAGE BASKETS,1,2011-06-02 14:30:00,24.95,13437.0,United Kingdom
211402,555368,22224,WHITE LOVEBIRD LANTERN,6,2011-06-02 14:30:00,2.95,13437.0,United Kingdom
211403,555368,20886,BOX OF 9 PEBBLE CANDLES,6,2011-06-02 14:30:00,1.95,13437.0,United Kingdom
211404,555368,22969,HOMEMADE JAM SCENTED CANDLES,12,2011-06-02 14:30:00,1.45,13437.0,United Kingdom
211405,555368,85174,S/4 CACTI CANDLES,4,2011-06-02 14:30:00,4.95,13437.0,United Kingdom
211406,555368,22928,YELLOW GIANT GARDEN THERMOMETER,2,2011-06-02 14:30:00,5.95,13437.0,United Kingdom
211407,555368,22927,GREEN GIANT GARDEN THERMOMETER,2,2011-06-0,NaN,NaN,NaN

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 211408 entries, 0 to 211407
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    211408 non-null  object
 1   StockCode    211408 non-null  object
 2   Description  210574 non-null  object
 3   Quantity     211408 non-null  int64
 4   InvoiceDate  211408 non-null  object
 5   UnitPrice    211407 non-null  float64
 6   CustomerID   150412 non-null  float64
 7   Country      211407 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 12.9+ MB

In [5]:
df.isnull().sum()

InvoiceNo          0
StockCode          0
Description      834
Quantity           0
InvoiceDate        0
UnitPrice          1
CustomerID     60996
Country            1
dtype: int64

In [6]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Quantity,211408.0,9.320262,234.368884,-74215.0,1.00,3.0,10.00,74215.00
UnitPrice,211407.0,5.023458,93.992483,0.0,1.25,2.1,4.21,16888.02
CustomerID,150412.0,15274.954119,1724.628700,12346.0,13831.00,15140.0,16807.00,18287.00

In [13]:
df.drop_duplicates(inplace=True)

In [16]:
df.shape

(209660, 8)

In [23]:
df["TotalSales"]= df["Quantity"] * df["UnitPrice"]

In [24]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalSales
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34

In [27]:
df["InvoiceDate"]=pd.to_datetime(df["InvoiceDate"], errors='coerce')

In [28]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalSales
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34

In [30]:
df["Month"]=df["InvoiceDate"].dt.month_name()

In [31]:
df["Month"]

0         December
1         December
2         December
3         December
4         December
            ...
211403        June
211404        June
211405        June
211406        June
211407         NaN
Name: Month, Length: 209660, dtype: object

In [32]:
print(df["TotalSales"].sum())

3736179.8509999993